common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pickever import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pickever/', include('pickever.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

pickever/urls.py
from django.urls import path
from . import views

app_name = 'pickever'

urlpatterns = [
    path('', views.index, name='index'),
    path('music/create/', views.music_create, name='music_create'),
    path('music/delete/<int:music_id>/', views.music_delete, name='music_delete'),
path('music/vote/<int:music_id>/', views.music_vote, name='music_vote'),
    path('report/create/<int:music_id>/', views.report_create, name='report_create'),
]

common/models.py
from django.db import models

# Create your models here.

pickever/models.py
from django.db import models
from django.contrib.auth.models import User


class Music(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter', blank=True)
    def __str__(self):
        return f'{self.title} - {self.artist}'

class Report(models.Model):
    content = models.TextField()
    reporting = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reporting')
    reported = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reported')
    reported_music= models.CharField(max_length=200)
    report_date = models.DateTimeField()
    def __str__(self):
        return self.content

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

pickever/forms.py
from django import forms
from pickever.models import Music, Report


class MusicForm(forms.ModelForm):
    class Meta:
        model = Music
        fields = ['title', 'artist']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'artist': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': '제목',
            'artist': '가수',
        }

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'content': '신고내용',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

pickever/views.py
from django.shortcuts import render, get_object_or_404, redirect
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Music, Report
from .forms import MusicForm, ReportForm


def index(request):
    music_list = Music.objects.order_by('create_date')
    context = {'music_list': music_list}
    return render(request, 'pickever/music_list.html', context)

@login_required(login_url='common:login')
def music_create(request):
    if request.method == 'POST':
        form = MusicForm(request.POST)
        if form.is_valid():
            music = form.save(commit=False)
            music.author = request.user
            music.create_date = datetime.datetime.now()
            music.save()
            return redirect('pickever:index')
    else:
        request_user_last_music = Music.objects.filter(author=request.user)
        if request_user_last_music.exists():
            request_user_last_music = request_user_last_music.order_by('create_date')
            request_user_last_music = request_user_last_music.last()
            last_music_time = request_user_last_music.create_date
            time_diff = datetime.datetime.now() - last_music_time
            if time_diff.seconds >= 600:
                form = MusicForm()
                context = {'form': form}
                return render(request, 'pickever/music_form.html', context)
            else:
                messages.error(request, '선곡 이후 10분이 지나야 재선곡이 가능합니다!')
                return redirect('pickever:index')
        else:
            form = MusicForm()
            context = {'form': form}
            return render(request, 'pickever/music_form.html', context)


@login_required(login_url='common:login')
def music_vote(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    if request.user == music.author:
        messages.error(request, '본인이 등록한 노래는 추천할 수 없습니다!')
    else:
        music.voter.add(request.user)
    return redirect('pickever:index')

def music_delete(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    if request.user != music.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', music_id=music.id)
    music.delete()
    return redirect('pickever:index')


@login_required(login_url='common:login')
def report_create(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            report = form.save(commit=False)
            report.reporting = request.user
            report.reported = music.author
            report.reported_music = music.title
            report.report_date = datetime.datetime.now()
            report.save()
            return redirect('pickever:index')
    else:
        form = ReportForm()
    context = {'form': form}
    return render(request, 'pickever/report_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Pickever</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-danger">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-danger">가입하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-danger border-bottom sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pickever:index' %}">Pickever</a>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
            <a class="btn btn-sm btn-light" href="{% url 'pickever:music_create' %}">음악 추가하기</a>
            </li>
        </ul>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" link href="https://docs.google.com/forms/d/e/1FAIpQLSe_oOv9Pc9zLtrM1UkmBsUXdJ3IDOU5-P4N1TnMlTyPkvj3Ug/viewform?usp=sf_link">설문조사</a>
                </li>
                <li>
                    <a class="nav-link" link href="https://pf.kakao.com/_nxdbzxj/chat">고객센터</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pickever/music_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">음악추가</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="artist" class="form-label">가수</label>
            <input type="text" class="form-control" name="artist" id="artist"
                   value="{{ form.artist.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="btn btn-danger">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pickever/music_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-4">♬<b>댄스나 랩/힙합 장르는 제외</b>하고 선곡해주세요♬{{text|linebreaks}}(댄스나 랩/힙합 장르 선곡 시 삭제됩니다.){{text|linebreaks}}
선곡은 <b>10분</b>마다 1곡씩 가능합니다.{{text|linebreaks}} 'pickever'를 이용하면서 느낀 점과 의견을 보내주세요! {{text|linebreaks}} 여러분들의 작은 도움이 더 나은 'pickever'을 만듭니다.{{text|linebreaks}} <b>설문조사</b> 많은 참여 부탁드려요!</div>
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <table class="table">
        <thead>
        <tr class="table-danger">
            <th>#</th>
            <th>음악</th>
            <th>작성일시</th>
            <th> </th>
            <th> </th>
        </tr>
        </thead>
        <tbody>
        {% if music_list %}
        {% for music in music_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {{ music.title }} - {{ music.artist }}</a>
            </td>
            <td>{{ music.create_date.time }}</td>
            <td class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'pickever:music_vote' music.id  %}"
               class="recommend btn btn-sm btn-outline-danger"> 추천
                <span class="badge rounded-pill bg-danger">{{music.voter.count}}</span>
            </a>
                 {% if request.user == music.author %}
                 <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-danger"
                    data-uri="{% url 'pickever:music_delete' music.id  %}">삭제</a>
                 {% endif %}
            </a>
                 {% if request.user != music.author %}
                  <a href= "{% url 'pickever:report_create' music.id  %}" class="btn btn-sm btn-outline-danger">신고</a>
                 {% endif %}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">음악이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pickever/report_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">신고</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">신고내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-danger">저장하기</button>
    </form>
</div>
{% endblock %}